{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "002766f2-90d3-4063-a642-ba77dcbf8936",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pdfplumber\n",
    "from PyPDF2 import PdfReader\n",
    "import re\n",
    "from datetime import datetime\n",
    "from langdetect import detect\n",
    "from sumy.parsers.plaintext import PlaintextParser\n",
    "from sumy.nlp.tokenizers import Tokenizer\n",
    "from sumy.summarizers.lsa import LsaSummarizer\n",
    "from sumy.nlp.stemmers import Stemmer\n",
    "from sumy.utils import get_stop_words\n",
    "import yake\n",
    "import jieba\n",
    "import tempfile\n",
    "import os\n",
    "\n",
    "# 页面配置\n",
    "st.set_page_config(page_title=\"文献伴侣\", page_icon=\"📚\")\n",
    "st.title(\"📚 文献伴侣智能体\")\n",
    "st.markdown(\"总结论文摘要 · 提取关键观点 · 生成 APA/MLA 引用\")\n",
    "\n",
    "def detect_language(text):\n",
    "    try:\n",
    "        lang = detect(text[:500])\n",
    "        return 'zh' if lang.startswith('zh') else 'en'\n",
    "    except:\n",
    "        return 'en'\n",
    "\n",
    "def get_text_from_pdf(uploaded_file):\n",
    "    text = \"\"\n",
    "    metadata = {}\n",
    "    with tempfile.NamedTemporaryFile(delete=False, suffix=\".pdf\") as tmp:\n",
    "        tmp.write(uploaded_file.read())\n",
    "        tmp_path = tmp.name\n",
    "    try:\n",
    "        with pdfplumber.open(tmp_path) as pdf:\n",
    "            for page in pdf.pages:\n",
    "                page_text = page.extract_text()\n",
    "                if page_text:\n",
    "                    text += page_text + \"\\n\"\n",
    "            if pdf.metadata:\n",
    "                metadata = pdf.metadata\n",
    "    except:\n",
    "        try:\n",
    "            reader = PdfReader(tmp_path)\n",
    "            if reader.metadata:\n",
    "                metadata = reader.metadata\n",
    "            for page in reader.pages:\n",
    "                page_text = page.extract_text()\n",
    "                if page_text:\n",
    "                    text += page_text + \"\\n\"\n",
    "        except Exception as e:\n",
    "            st.error(f\"PDF读取失败: {e}\")\n",
    "    os.unlink(tmp_path)\n",
    "    return text.strip(), metadata\n",
    "\n",
    "def get_summary(text, lang, sentence_count=4):\n",
    "    try:\n",
    "        if lang == 'zh':\n",
    "            sentences = re.split(r'[。！？!?]', text)\n",
    "            sentences = [s.strip() for s in sentences if len(s.strip()) > 20]\n",
    "            return sentences[:sentence_count] if sentences else []\n",
    "        else:\n",
    "            parser = PlaintextParser.from_string(text, Tokenizer(\"english\"))\n",
    "            stemmer = Stemmer(\"english\")\n",
    "            summarizer = LsaSummarizer(stemmer)\n",
    "            summarizer.stop_words = get_stop_words(\"english\")\n",
    "            summary = summarizer(parser.document, sentence_count)\n",
    "            return [str(s) for s in summary]\n",
    "    except:\n",
    "        return []\n",
    "\n",
    "def extract_keywords(text, lang, num_keywords=3):\n",
    "    try:\n",
    "        lan = 'zh' if lang == 'zh' else 'en'\n",
    "        kw_extractor = yake.KeywordExtractor(lan=lan, top=num_keywords, dedupLim=0.9)\n",
    "        keywords = kw_extractor.extract_keywords(text)\n",
    "        return [kw[0] for kw in keywords]\n",
    "    except:\n",
    "        return []\n",
    "\n",
    "def format_citations(authors, title, year, journal, volume, pages):\n",
    "    # 简化版APA/MLA（与之前相同逻辑，略作精简）\n",
    "    author_list = []\n",
    "    for item in authors.split(';'):\n",
    "        name = item.strip()\n",
    "        if not name:\n",
    "            continue\n",
    "        if ',' in name:\n",
    "            last, first = name.split(',', 1)\n",
    "            author_list.append((last.strip(), first.strip()))\n",
    "        else:\n",
    "            parts = name.split()\n",
    "            if len(parts) == 1:\n",
    "                author_list.append((parts[0], ''))\n",
    "            else:\n",
    "                author_list.append((parts[-1], ' '.join(parts[:-1])))\n",
    "    apa_authors = []\n",
    "    for last, first in author_list:\n",
    "        if first:\n",
    "            initials = ''.join([n[0]+'.' for n in first.split() if n])\n",
    "            apa_authors.append(f\"{last}, {initials}\")\n",
    "        else:\n",
    "            apa_authors.append(last)\n",
    "    if len(apa_authors) == 1:\n",
    "        apa_auth_str = apa_authors[0]\n",
    "    elif len(apa_authors) == 2:\n",
    "        apa_auth_str = f\"{apa_authors[0]} & {apa_authors[1]}\"\n",
    "    else:\n",
    "        apa_auth_str = \", \".join(apa_authors[:-1]) + \", & \" + apa_authors[-1]\n",
    "\n",
    "    if len(author_list) == 1:\n",
    "        last, first = author_list[0]\n",
    "        mla_auth_str = f\"{last}, {first}\" if first else last\n",
    "    elif len(author_list) == 2:\n",
    "        last1, first1 = author_list[0]\n",
    "        last2, first2 = author_list[1]\n",
    "        mla_auth_str = f\"{last1}, {first1}, and {first2} {last2}\" if first1 and first2 else f\"{last1} and {last2}\"\n",
    "    else:\n",
    "        last1, first1 = author_list[0]\n",
    "        mla_auth_str = f\"{last1}, {first1 if first1 else ''} et al.\"\n",
    "\n",
    "    apa_cite = f\"{apa_auth_str} ({year}). {title}. {journal}\"\n",
    "    if volume:\n",
    "        apa_cite += f\", {volume}\"\n",
    "    if pages:\n",
    "        apa_cite += f\", {pages}\"\n",
    "    apa_cite += \".\"\n",
    "    mla_cite = f'{mla_auth_str}. \"{title}.\" {journal}'\n",
    "    if volume:\n",
    "        mla_cite += f\", vol. {volume}\"\n",
    "    if pages:\n",
    "        mla_cite += f\", pp. {pages}\"\n",
    "    mla_cite += f\", {year}.\"\n",
    "    return apa_cite, mla_cite\n",
    "\n",
    "# 界面布局\n",
    "input_method = st.radio(\"选择输入方式\", (\"粘贴文本\", \"上传PDF文件\"))\n",
    "\n",
    "text = \"\"\n",
    "if input_method == \"粘贴文本\":\n",
    "    text = st.text_area(\"请输入论文全文\", height=300)\n",
    "else:\n",
    "    uploaded = st.file_uploader(\"上传PDF文件\", type=\"pdf\")\n",
    "    if uploaded:\n",
    "        with st.spinner(\"提取PDF文本...\"):\n",
    "            text, meta = get_text_from_pdf(uploaded)\n",
    "        if text:\n",
    "            st.success(f\"提取成功，共 {len(text)} 字符\")\n",
    "        else:\n",
    "            st.error(\"PDF无法提取文字，请检查是否扫描版\")\n",
    "\n",
    "if text:\n",
    "    lang = detect_language(text)\n",
    "    st.info(f\"检测到语言：{'中文' if lang=='zh' else '英文'}\")\n",
    "    with st.spinner(\"生成摘要和关键词...\"):\n",
    "        sentences = get_summary(text, lang)\n",
    "        core = sentences[0] if sentences else \"\"\n",
    "        detail = \" \".join(sentences[1:4]) if len(sentences) > 1 else \"\"\n",
    "        keywords = extract_keywords(text, lang)\n",
    "\n",
    "    # 引用信息输入\n",
    "    st.markdown(\"### 📖 引用信息（用于生成APA/MLA）\")\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        title = st.text_input(\"标题\")\n",
    "        authors = st.text_input(\"作者（多作者用分号;分隔）\")\n",
    "        year = st.text_input(\"发表年份\")\n",
    "    with col2:\n",
    "        journal = st.text_input(\"期刊/会议名称\")\n",
    "        volume = st.text_input(\"卷号（可选）\")\n",
    "        pages = st.text_input(\"页码（可选）\")\n",
    "\n",
    "    if title and authors and year and journal:\n",
    "        apa, mla = format_citations(authors, title, year, journal, volume, pages)\n",
    "    else:\n",
    "        apa = mla = \"请填写完整的标题、作者、年份、期刊\"\n",
    "\n",
    "    # 结果展示\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"### 📌 核心观点\")\n",
    "    st.write(core if core else \"（未能生成）\")\n",
    "\n",
    "    st.markdown(\"### 🔑 关键发现/论点\")\n",
    "    for i, kw in enumerate(keywords, 1):\n",
    "        st.write(f\"{i}. {kw}\")\n",
    "\n",
    "    st.markdown(\"### 📄 详细摘要\")\n",
    "    st.write(detail if detail else \"（未能生成）\")\n",
    "\n",
    "    st.markdown(\"### 📖 参考文献\")\n",
    "    st.markdown(f\"**APA**  \\n{apa}\")\n",
    "    st.markdown(f\"**MLA**  \\n{mla}\")\n",
    "\n",
    "    # 下载结果\n",
    "    md_content = f\"\"\"# 文献伴侣分析报告\n",
    "生成时间：{datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\n",
    "\n",
    "## 核心观点\n",
    "{core}\n",
    "\n",
    "## 关键发现/论点\n",
    "{chr(10).join([f\"{i+1}. {kw}\" for i,kw in enumerate(keywords)])}\n",
    "\n",
    "## 详细摘要\n",
    "{detail}\n",
    "\n",
    "## 参考文献\n",
    "**APA**  \n",
    "{apa}\n",
    "\n",
    "**MLA**  \n",
    "{mla}\n",
    "\"\"\"\n",
    "    st.download_button(\"📥 下载报告 (Markdown)\", md_content, file_name=f\"文献伴侣_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md\", mime=\"text/markdown\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
